### ISSUE TITLE
Failing build with GitHub Actions for publishableKey.

### ISSUE THREAD

**Issue by BiskremMuhammad** [clerkinc/javascript#1597]
I'm having a project with next js app and firebase, and i'm using GitHub actions to deploy to firebase hosting.

the workflow is failing on `yarn run build` command, for this reason

```
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
```

I'm having the publishableKey defined in repo secrets it didn't work,
i've also tried to add it to `with` entry in the workflow, it also didn't work.
i even passed `publishableKey` as a prop to ClerkProvider from env vars it also didn't work

and this is the workflow .`yml` file

```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install && yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}"
          CLERK_SECRET_KEY: "${{secrets.CLERK_SECRET_KEY}}"
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          publishableKey: "${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STORELIFE_90955 }}"
```

**Comment by BRKalow** [comment]
Hey @BiskremMuhammad, it looks like you're not passing the environment variables to the build step in your job, so Next.js can't embed them into the build artifact. Can you try specifying the Clerk environment variables here instead:

```
- run: yarn install && yarn run build
  env:
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}"
    CLERK_SECRET_KEY: "${{secrets.CLERK_SECRET_KEY}}"
```
