### ISSUE TITLE
Embed Clerk React components to site with root's element font-size 1px;

### ISSUE THREAD

**Issue by visortelle** [clerkinc/javascript#633]
Hi!

For our site we have the following global CSS:
 
```css
:root, 
:host {
  font-size: 1px;
}
```

We do it to use clear sizes like 12rem, 18rem, 24rem in our styles. We don't want to sit with a calculator for 0.35rem, 0.68rem, etc.

This is how `<UserProfile />` component looks on our page.

<img width="640" alt="Screenshot 2022-12-24 at 9 33 53 AM" src="https://user-images.githubusercontent.com/9302460/209431042-c8a845e6-5393-4d24-a4f1-869b0bf08d5e.png">

I'm not CSS pro, but probably you can consider switching to custom units like those described here:
https://github.com/w3c/csswg-drafts/issues/7613
https://github.com/w3c/csswg-drafts/issues/7379

I mean something like:

```css
:root {
  --cl-px: 1rem; /* Your customer can override this variable in his code. */
}

/* In your code it could look like it. */
.cl-card {
  max-width: calc(320 * var(--cl-px));
}
```

This way you can don't worry anymore that some customers for some reason use non-16px rems.

If you know a less ugly way to fix it on our side, please tell me.

Now we'll just spend a couple of hours rewriting our CSS to px. Not a big deal for the current project, but it would be great if we could use Clerk React components in other projects without rewriting our styles.

Thank you.
